version: '3.9'

services:
  normalizer:
    build:
      context: .
      dockerfile: Dockerfile
    image: normalizer_service
    container_name: normalizer
    environment:
      - COMM_TYPE=REST
      - LOG_DEBUG=1
      - NORMALIZER_PORT=8080
    ports:
      - "8080:8080"

  alpha:
    build:
      context: .
      dockerfile: alpha.Dockerfile
    container_name: alpha
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - COMM_TYPE=REST
      - NORMALIZER_HOST=normalizer
      - NORMALIZER_PORT=8080
    command: ["python", "alpha_service.py"]
    depends_on:
      - normalizer

  master:
    build:
      context: .
      dockerfile: master.Dockerfile
    container_name: master
    working_dir: /app
    volumes:
      - ./:/app
    command: ["python", "master.py"]
    depends_on:
      - alpha

networks:
  default:
    name: cst435_net

