services:
  worker1:
    build: .
    command: ["python", "map_reduce_Worker.py", "50051"]
    ports:
      - "50051:50051"
    networks:
      - mapreduce-network

  worker2:
    build: .
    command: ["python", "map_reduce_Worker.py", "50052"]
    ports:
      - "50052:50052"
    networks:
      - mapreduce-network
  worker3:
    build: .
    command: ["python", "map_reduce_Worker.py", "50053"]
    ports:
      - "50053:50053"
    networks:
      - mapreduce-network


  master:
    build: .
    command: ["python", "map_reduce_Master_docker.py"]
    volumes:
      - ./input_data:/app/input_data
    depends_on:
      - worker1
      - worker2
      - worker3
    networks:
      - mapreduce-network
    # extra_hosts:
    #   - "arch-worker:host-gateway"  # Maps to Windows host IP

networks:
  mapreduce-network:
    driver: bridge