# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gRPC_service_defination_pb2 as gRPC__service__defination__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gRPC_service_defination_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MapReduceStub(object):
    """The main service definition for the Master-Worker communication.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MapTask = channel.unary_unary(
                '/mapreduce.MapReduce/MapTask',
                request_serializer=gRPC__service__defination__pb2.MapRequest.SerializeToString,
                response_deserializer=gRPC__service__defination__pb2.MapResponse.FromString,
                _registered_method=True)
        self.ReduceTask = channel.unary_unary(
                '/mapreduce.MapReduce/ReduceTask',
                request_serializer=gRPC__service__defination__pb2.ReduceRequest.SerializeToString,
                response_deserializer=gRPC__service__defination__pb2.ReduceResponse.FromString,
                _registered_method=True)
        self.FullProcessTask = channel.unary_unary(
                '/mapreduce.MapReduce/FullProcessTask',
                request_serializer=gRPC__service__defination__pb2.MapRequest.SerializeToString,
                response_deserializer=gRPC__service__defination__pb2.MapResponse.FromString,
                _registered_method=True)


class MapReduceServicer(object):
    """The main service definition for the Master-Worker communication.
    """

    def MapTask(self, request, context):
        """Master calls this RPC to assign a Map task to a worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReduceTask(self, request, context):
        """Master calls this RPC to assign a Reduce task to a worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FullProcessTask(self, request, context):
        """Master calls this RPC to let a worker handle the *entire* process:
        perform mapping and local reduction before returning results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapReduceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MapTask': grpc.unary_unary_rpc_method_handler(
                    servicer.MapTask,
                    request_deserializer=gRPC__service__defination__pb2.MapRequest.FromString,
                    response_serializer=gRPC__service__defination__pb2.MapResponse.SerializeToString,
            ),
            'ReduceTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReduceTask,
                    request_deserializer=gRPC__service__defination__pb2.ReduceRequest.FromString,
                    response_serializer=gRPC__service__defination__pb2.ReduceResponse.SerializeToString,
            ),
            'FullProcessTask': grpc.unary_unary_rpc_method_handler(
                    servicer.FullProcessTask,
                    request_deserializer=gRPC__service__defination__pb2.MapRequest.FromString,
                    response_serializer=gRPC__service__defination__pb2.MapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mapreduce.MapReduce', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mapreduce.MapReduce', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MapReduce(object):
    """The main service definition for the Master-Worker communication.
    """

    @staticmethod
    def MapTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapreduce.MapReduce/MapTask',
            gRPC__service__defination__pb2.MapRequest.SerializeToString,
            gRPC__service__defination__pb2.MapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReduceTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapreduce.MapReduce/ReduceTask',
            gRPC__service__defination__pb2.ReduceRequest.SerializeToString,
            gRPC__service__defination__pb2.ReduceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FullProcessTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapreduce.MapReduce/FullProcessTask',
            gRPC__service__defination__pb2.MapRequest.SerializeToString,
            gRPC__service__defination__pb2.MapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
